import { post } from '@/utils/methods'

export interface ExcelParam {
    // Table 1 —— 电器检验(单)表
    tableCode?: string,
    projectName?: string,
    cabinetType?: string,
    cabinetNum?: string,
    inspector?: string,
    date?: string,
    other?: string,
    remark?: string,

    // Table 2 —— 装备检验表
    testerNum?: string,
    powerOnNum?: string,
    proLoopNum?: string,
    drawerConfirm?: number,
    processConfirm?: number,
    transferListConfirm?: number,

    // Table 3 —— 回路检验表
    loopVdc?: string,
    voltage?: string,
    formula?: string,
    l1Prevoltage?: string,
    l2Prevoltage?: string,
    l3Prevoltage?: string,
    nPrevoltage?: string,
    assistPrevoltage?: string,
    l1NoPrevoltage?: string,
    l2NoPrevoltage?: string,
    l3NoPrevoltage?: string,
    nNoPrevoltage?: string,
    assistNoPrevoltage?: string,
    l1LeakageCurrent?: string,
    l2LeakageCurrent?: string,
    l3LeakageCurrent?: string,
    nLeakageCurrent?: string,
    assistLeakageCurrent?: string,

    // Table 4 —— 检验项表
    locationResult?: number,
    locationCorrector?: string,
    locationRetest?: string,
    phaseSequenceResult?: number,
    phaseSequenceCorrector?: string,
    phaseSequenceRetest?: string,
    secondaryElementResult?: number,
    secondaryElementCorrector?: string,
    secondaryElementRetest?: string,
    lightResult?: number,
    lightCorrector?: string,
    lightRetest?: string,
    meterShowResult?: number,
    meterShowCorrector?: string,
    meterShowRetest?: string,
    meterParamResult?: number,
    meterParamCorrector?: string,
    meterParamRetest?: string,
    signalResult?: number,
    signalCorrector?: string,
    signalRetest?: string,
    electricLinkageResult?: number,
    electricLinkageCorrector?: string,
    electricLinkageRetest?: string,
    cableInterlockResult?: number,
    cableInterlockCorrector?: string,
    cableInterlockRetest?: string,
    allFunctionResult?: number,
    allFunctionCorrector?: string,
    allFunctionRetest?: string,
    powerControllerResult?: number,
    powerControllerCorrector?: string,
    powerControllerRetest?: string,
    switchResult?: number,
    switchCorrector?: string,
    switchRetest?: string,
    fanTemperatureResult?: number,
    fanTemperatureCorrector?: string,
    fanTemperatureRetest?: string,
    arresterResult?: number,
    arresterCorrector?: string,
    arresterRetest?: string,
    doorLandResult?: number,
    doorLandCorrector?: string,
    doorLandRetest?: string,
    elementLandResult?: number,
    elementLandCorrector?: string,
    elementLandRetest?: string,
    specialPointResult?: number,
    specialPointCorrector?: string,
    specialPointRetest?: string,
    blotResult?: number,
    blotCorrector?: string,
    blotRetest?: string,
    sundriesResult?: number,
    sundriesCorrector?: string,
    sundriesRetest?: string,

    // Table 5 —— 其它不合格项表
    oneText?: string,
    twoText?: string,
    threeText?: string,
    fourText?: string,
    fiveText?: string,
    sixText?: string,
    oneCorrector?: string,
    twoCorrector?: string,
    threeCorrector?: string,
    fourCorrector?: string,
    fiveCorrector?: string,
    sixCorrector?: string,
    oneRecheck?: string,
    twoRecheck?: string,
    threeRecheck?: string,
    fourRecheck?: string,
    fiveRecheck?: string,
    sixRecheck?: string,
}

export function excelRequest(params: ExcelParam) {
    return post('/excel/upload', params); //测试接口
}